import type { Product } from "./product-types";

type SeedRow = [
  slug: string,
  name: string,
  category: string,
  audience: string,
  problem: string,
  promise: string,
  differentiator: string,
];

const rows: SeedRow[] = [
  // Finance and revenue operations
  ["overdue-invoice-rescue", "Invoice Rescue", "Finance operations", "small agencies and consultancies", "Overdue invoice follow-ups, disputes, and promises to pay disappear into inboxes.", "Turn every overdue invoice into a calm, timed recovery sequence.", "Changes tone and next steps based on invoice age, client history, disputes, and promised dates."],
  ["contractor-change-order-ledger", "Change Order Ledger", "Construction finance", "specialty contractors", "Verbal scope changes become unpaid work because approval evidence and field notes are scattered.", "Capture, price, approve, and collect every scope change.", "Links photos, labor notes, pricing, and approval into one billing-ready audit trail."],
  ["saas-renewal-radar", "Renewal Radar", "Software spend", "finance and IT teams", "Renewal dates and notice windows are missed while unused seats quietly inflate contracts.", "Create enough lead time to cancel, resize, or renegotiate every SaaS renewal.", "Treats the cancellation-notice deadline as the real renewal date and assembles usage evidence first."],
  ["marketplace-fee-reconciler", "Marketplace Fee Reconciler", "E-commerce finance", "multi-marketplace sellers", "Settlement deposits do not cleanly match orders, refunds, reserves, and platform fees.", "Explain every marketplace payout down to the order and fee.", "Reconstructs payouts as traceable ledgers and packages unexplained deductions for claims."],
  ["grant-spend-guard", "Grant Spend Guard", "Nonprofit finance", "small nonprofit finance teams", "Restricted expenses are charged to the wrong fund, period, or budget line and found too late.", "Catch grant-spend exceptions before reporting deadlines.", "Checks every expense against restrictions, approved categories, grant dates, and required evidence."],
  ["freight-invoice-auditor", "Freight Invoice Auditor", "Logistics finance", "small shippers", "Duplicate charges, wrong accessorials, and missed service refunds hide inside carrier invoices.", "Find recoverable freight charges before dispute windows close.", "Tests each charge against tracking events, contracted rates, service outcomes, and carrier deadlines."],
  ["subscription-margin-mapper", "Subscription Margin Mapper", "SaaS finance", "usage-heavy software companies", "Vendor usage and support costs make individual accounts unprofitable even when revenue looks healthy.", "Show true contribution margin for every plan and customer.", "Maps infrastructure, model, data, and support costs to the same account and billing period as revenue."],
  ["multi-location-deposit-matcher", "Deposit Matcher", "Multi-location finance", "franchises and clinics", "Net deposits and timing differences leave location-level revenue unreconciled.", "Match deposits to locations, processors, batches, and business dates.", "Models split deposits, fees, weekends, and batch cutoffs instead of requiring exact amounts."],
  ["usage-billing-anomaly-watch", "Usage Billing Watch", "Revenue operations", "metered software companies", "Missing, duplicated, or late usage events become incorrect invoices and customer disputes.", "Detect metering gaps before usage becomes an invoice.", "Compares product telemetry, aggregation rules, allowances, and draft invoice lines before billing."],
  ["commission-clawback-calculator", "Clawback Calculator", "Sales compensation", "revenue operations teams", "Commission reversals after refunds or churn are inconsistent and hard for reps to verify.", "Make every commission adjustment reproducible and explainable.", "Snapshots the original plan version and shows the exact rule path behind each clawback."],

  // Sales and customer operations
  ["rfp-answer-curator", "RFP Answer Curator", "B2B sales", "specialized vendors", "Teams reuse stale questionnaire answers without knowing which evidence or approver supported them.", "Reuse approved answers without recycling outdated claims.", "Gives each answer an owner, source, freshness date, product scope, and confidence warning."],
  ["technical-demo-followup", "Demo Thread", "Sales engineering", "sales engineers", "Buyer questions, promised artifacts, and technical risks vanish into notes after demos.", "Turn every technical demo into a complete follow-up plan.", "Separates objections, validation tasks, promised assets, and decision criteria with proof owners."],
  ["lost-deal-pattern-miner", "Loss Pattern Miner", "Revenue intelligence", "founder-led sales teams", "Closed-lost labels hide recurring product gaps, timing issues, and positioning mistakes.", "Convert lost-deal evidence into specific experiments.", "Distinguishes seller-entered reasons from actual buyer language in calls and emails."],
  ["territory-overlap-resolver", "Territory Resolver", "Sales operations", "growing sales teams", "Duplicate prospecting and unclear corporate hierarchies create ownership conflicts.", "Resolve account ownership before two reps contact the same company.", "Evaluates hierarchy, geography, segment rules, relationships, and named-account exceptions together."],
  ["channel-partner-handoff", "Partner Handoff", "Channel sales", "vendors working with referral and reseller partners", "Partner-sourced context is lost between registration, sales, scoping, and implementation.", "Keep the customer story intact across every partner handoff.", "Records source credit, commitments, responsibilities, and visibility boundaries in a shared deal brief."],
  ["technical-evaluation-tracker", "Evaluation Proofboard", "Enterprise sales", "software vendors running proofs of concept", "Test cases expand without clear success criteria, owners, evidence, or a decision date.", "Keep every evaluation tied to a buyer-approved proof plan.", "Requires every test to connect to a decision criterion and a buyer-readable result."],
  ["renewal-risk-briefs", "Renewal Brief", "Customer success", "customer success teams", "Renewal risk is reduced to a subjective color instead of evidence about adoption and outcomes.", "Give every renewal a defensible risk and value brief.", "Separates observable evidence from account-team judgment and names the missing facts."],
  ["industrial-lead-qualifier", "SpecFit Qualifier", "Industrial sales", "manufacturers handling technical inquiries", "Engineering time is spent on requests that miss basic tolerance, material, volume, or certification needs.", "Qualify technical fit before routing a request to engineering.", "Asks product-line-specific questions and explains fit, exception, or capability mismatch."],
  ["proposal-scope-checker", "ScopeCheck", "Professional services sales", "consultancies", "Ambiguous responsibilities and missing dependencies turn signed proposals into margin-eroding work.", "Find scope ambiguity before a proposal reaches the client.", "Checks deliverables, exclusions, dependencies, acceptance criteria, and revision limits together."],
  ["pricing-exception-log", "Price Exception Log", "Deal desk", "B2B revenue teams", "Discount decisions are inconsistent because precedent, rationale, and give-gets are not searchable.", "Make every pricing exception fast, consistent, and reviewable.", "Links requests to comparable decisions and requires an explicit exchange for value."],

  // Marketing and SEO
  ["local-service-page-gap-finder", "Local Page Gap Finder", "Local SEO", "multi-location service businesses", "Teams publish near-duplicate city pages without knowing which local questions deserve distinct coverage.", "Prioritize location pages that answer distinct local demand.", "Requires unique intent, local proof, service boundaries, and a reason not to merge each page."],
  ["comparison-content-planner", "Comparison Brief", "Product marketing", "B2B marketers", "Comparison pages repeat shallow feature grids instead of explaining real buyer tradeoffs.", "Build honest comparison pages around decision criteria.", "Organizes differences by buyer context, switching cost, operating constraints, and evidence quality."],
  ["customer-question-miner", "Question Mine", "Content research", "small product teams", "Specific unanswered customer questions stay buried across calls, tickets, and communities.", "Turn recurring customer questions into evidence-backed content briefs.", "Preserves original wording, situation, and buying stage instead of flattening questions into keywords."],
  ["newsletter-sponsor-matcher", "Sponsor Fit", "Newsletter monetization", "independent newsletter publishers", "Publishers chase broad sponsor lists without a clear audience-to-offer fit.", "Rank sponsor prospects by specific audience and campaign fit.", "Matches reader jobs and advertiser timing signals, then drafts a testable fit thesis."],
  ["review-response-coach", "Review Reply Coach", "Reputation operations", "multi-location local businesses", "Generic or defensive review replies miss the operational issue and can worsen complaints.", "Write specific, policy-safe replies and route the underlying issue.", "Separates the public response from the private recovery task and checks known facts."],
  ["video-chapter-seo", "ChapterCraft", "Video SEO", "educational video creators", "Useful answers stay hidden inside long videos because chapters and descriptions are vague.", "Turn spoken answers into precise, searchable chapters.", "Names chapters after concrete questions, preserves timestamps, and avoids keyword stuffing."],
  ["ecommerce-taxonomy-doctor", "Taxonomy Doctor", "E-commerce SEO", "stores with sprawling catalogs", "Overlapping categories, empty filters, and unstable labels confuse shoppers and search engines.", "Design a catalog structure people can browse and search engines can understand.", "Evaluates shopper language, inventory coverage, URL duplication, and merchandising ownership together."],
  ["content-decay-alerts", "Content Decay Alerts", "SEO operations", "evergreen content teams", "Traffic declines are noticed late and seasonality, stale facts, ranking loss, and intent shifts blur together.", "Detect meaningful decay and prescribe the smallest useful update.", "Compares query mix, SERP change, page history, and freshness before recommending a rewrite."],
  ["keyword-cannibalization-map", "Intent Collision Map", "SEO operations", "large content sites", "Teams cannot distinguish healthy multi-page coverage from harmful keyword cannibalization.", "Separate genuine cannibalization from useful intent coverage.", "Compares page purpose, query overlap, ranking swaps, internal links, and conversion roles."],
  ["webinar-repurposing-map", "Webinar Content Map", "Content operations", "B2B content teams", "One webinar becomes many shallow assets because claims, examples, and questions are not separated.", "Turn a webinar into useful, nonduplicative resources.", "Maps every derivative asset to a distinct job and preserves source timestamps."],

  // Workforce and governance
  ["hourly-shift-swap", "Shift Swap Guard", "Workforce operations", "restaurants and retail teams", "Informal shift swaps create uncovered roles, overtime surprises, and fairness concerns.", "Approve safe shift swaps without manager message chaos.", "Checks qualification, rest rules, overtime, availability, and acceptance before changing the schedule."],
  ["certification-expiry-board", "Credential Clock", "Workforce compliance", "field-service employers", "Expired credentials are discovered while scheduling a worker or during an audit.", "Renew every required credential before it blocks work.", "Maps each credential to the jobs, jurisdictions, and customers it qualifies."],
  ["interview-consistency-kit", "Interview Consistency Kit", "Recruiting operations", "small hiring teams", "Candidates are evaluated on different questions and vague impressions.", "Make every interview comparable, job-relevant, and timely.", "Ties questions and evidence to competencies and hides peer feedback until submission."],
  ["return-to-work-coordinator", "Return Plan", "People operations", "HR teams", "Work parameters, equipment, access, schedules, and expectations are coordinated through sensitive email threads.", "Organize a respectful return after extended leave without oversharing.", "Separates confidential records from the minimum operational information each participant needs."],
  ["field-tech-onboarding", "FieldReady", "Field service operations", "service companies onboarding technicians", "Generic training completion does not prove readiness for specific field tasks.", "Verify job readiness one field skill at a time.", "Combines observed sign-off, equipment authorization, site prerequisites, and verifier identity."],
  ["contractor-offboarding", "Clean Exit", "Security operations", "companies using many contractors", "Temporary accounts, shared files, keys, and client access remain active after contracts end.", "Prove that every contractor access path was closed.", "Starts from actual identities, projects, devices, repositories, and shared credentials."],
  ["pto-coverage-planner", "Coverage Map", "Team operations", "small operational teams", "Time off is approved without seeing which duties, approvals, or customer commitments lose an owner.", "Approve leave with explicit, lightweight coverage.", "Derives coverage needs from recurring work and upcoming commitments rather than a blank handoff."],
  ["frontline-incident-debrief", "Debrief Loop", "Operational learning", "frontline service teams", "Incident reviews assign blame or produce vague lessons that never change a process.", "Turn incident evidence into owned, testable improvements.", "Builds a neutral multi-perspective timeline and verifies whether corrective actions worked."],
  ["policy-acknowledgement-evidence", "Policy Proof", "People compliance", "distributed businesses", "A click confirms receipt but not which policy version was read or what changed.", "Make policy acknowledgement versioned, specific, and auditable.", "Highlights changed clauses, records the exact version, and routes private questions."],
  ["role-expectation-calibrator", "Role Calibrator", "Talent management", "growing companies", "Promotion and hiring decisions rely on titles without shared evidence of scope and impact.", "Make role expectations comparable without forcing identical jobs.", "Calibrates common dimensions while preserving function-specific evidence and legitimate differences."],

  // Compliance and legal operations
  ["privacy-request-inbox", "Privacy Request Inbox", "Privacy operations", "small businesses", "Data access and deletion requests span channels, systems, identity checks, and deadlines.", "Coordinate each privacy request from intake to defensible completion.", "Minimizes identity evidence and preserves reasoning behind exceptions and redactions."],
  ["vendor-security-evidence", "Vendor Evidence Room", "Security compliance", "small software vendors", "Teams repeatedly send stale security artifacts without tracking scope, freshness, or access.", "Share the minimum current evidence for each buyer review.", "Matches each question to approved evidence, redaction level, owner, and expiration date."],
  ["accessibility-issue-tracker", "AccessFix", "Digital accessibility", "product teams", "Scanner results, user reports, design fixes, and regression evidence live in separate tools.", "Move accessibility barriers from evidence to verified remediation.", "Groups findings by user barrier and component root cause, then requires verification."],
  ["food-label-claim-checker", "Label Claim Checklist", "Food compliance", "small packaged-food brands", "Marketing claims, formula changes, allergens, and evidence are reviewed in disconnected files.", "Organize label evidence before qualified regulatory review.", "Links each claim to package location, formula version, evidence owner, and review status."],
  ["construction-lien-calendar", "Lien Clock", "Construction administration", "contractors", "Jurisdiction-specific notice dates and delivery evidence drift in spreadsheets.", "Surface notice deadlines with source facts for professional review.", "Records the event and jurisdiction assumptions behind each date instead of giving unsupported certainty."],
  ["nonprofit-board-minute-builder", "Board Record", "Nonprofit governance", "small nonprofit boards", "Minutes become transcripts or omit motions, recusals, votes, and assigned actions.", "Produce concise governance records with visible follow-through.", "Distinguishes discussion from formal action and links decisions to agenda items."],
  ["lease-abstract-review", "Lease Signal", "Commercial real estate", "small property teams", "Renewal options, expense rules, duties, and notice dates stay buried in leases and amendments.", "Turn each lease into a reviewable operating brief.", "Links every abstracted term to its clause and flags conflicts for human review."],
  ["export-restriction-checklist", "Export Review Desk", "Trade compliance", "small manufacturers", "Party, destination, classification, and end-use checks happen inconsistently before orders.", "Assemble a complete export review packet for qualified approval.", "Preserves the source and date of screening results and separates flags from decisions."],
  ["certificate-of-insurance-chaser", "COI Chaser", "Vendor compliance", "property managers and contractors", "Expired certificates and missing endorsements are found after vendor work is scheduled.", "Collect and review insurance evidence before work begins.", "Extracts certificate fields, compares job requirements, and keeps review separate from collection."],
  ["ai-use-case-registry", "AI Use Registry", "AI governance", "companies adopting many AI tools", "Teams cannot answer where AI is used, what data enters it, or how outputs affect decisions.", "Maintain a living map of organizational AI use.", "Inventories use cases rather than vendors and ties each to data, oversight, owner, and review."],

  // Commerce and local services
  ["return-reason-lab", "Return Reason Lab", "E-commerce operations", "online brands", "Broad return codes hide sizing, expectation, damage, fulfillment, and quality causes.", "Turn return evidence into specific product and merchandising fixes.", "Connects customer language, SKU attributes, photos, batch, and fulfillment path before clustering."],
  ["bundle-margin-optimizer", "Bundle Margin Planner", "E-commerce merchandising", "direct-to-consumer brands", "Bundles lose money after discounts, pick costs, dimensional weight, and stock imbalance.", "Design bundles that improve conversion without hiding margin damage.", "Models contribution margin, fulfillment complexity, inventory risk, and use-case coherence."],
  ["preorder-promise-tracker", "Preorder Promise", "E-commerce operations", "brands selling preorders", "Customer promises drift away from production, freight, and fulfillment milestones.", "Keep every preorder promise synchronized with delivery risk.", "Maps customer cohorts to real supply milestones and drafts updates from what changed."],
  ["wholesale-moq-planner", "MOQ Planner", "Wholesale operations", "small product brands", "Sales accepts assortments that violate supplier minimums, case packs, or packaging constraints.", "Quote wholesale assortments that respect real operating limits.", "Translates buyer quantities into component, case, color, and supplier minimums with exception costs."],
  ["marketplace-listing-drift", "Listing Drift Watch", "Marketplace operations", "brands selling across channels", "Titles, claims, specifications, and variants diverge from the approved product source.", "Detect material listing drift before customers do.", "Classifies differences by customer harm, compliance risk, discoverability, or harmless formatting."],
  ["parcel-damage-evidence", "Damage Claim Kit", "Shipping operations", "merchants filing carrier claims", "Photos, packaging details, value proof, and deadlines are collected after evidence is discarded.", "Capture a claim-ready damage record while evidence still exists.", "Asks carrier-specific evidence questions and checks completeness before packaging is thrown away."],
  ["sku-discontinuation-planner", "SKU Sunset", "Inventory planning", "consumer brands", "Stopping purchases leaves orphan inventory, broken bundles, stale listings, and support obligations.", "Retire a SKU without creating operational debris.", "Maps dependencies across components, channels, customers, content, warranties, and contracts."],
  ["subscription-skip-signals", "Skip Signal", "Subscription commerce", "physical subscription brands", "Brands treat skips as failure instead of evidence about cadence, stockpiling, or preference.", "Learn why customers skip and offer a helpful adjustment.", "Uses skip sequences and volunteered reasons without dark patterns or unwanted shipments."],
  ["apparel-fit-feedback", "Fit Evidence", "Apparel commerce", "small apparel brands", "Runs-small labels ignore garment measurements, style intent, preference, and variant differences.", "Turn fit feedback into precise sizing and product changes.", "Separates measurement issues from preference while avoiding unnecessary sensitive body data."],
  ["catalog-enrichment-qa", "Catalog QA Gate", "Product information management", "retailers enriching large catalogs", "Generated attributes introduce unsupported claims, wrong units, and variant inconsistencies.", "Publish enriched catalog data only when traceable and consistent.", "Validates each field against source evidence, taxonomy, sibling variants, and confidence thresholds."],

  // Local and property operations
  ["dental-recall-gap-list", "Recall Gap List", "Dental administration", "independent dental practices", "Recall lists mix overdue patients with completed, transferred, or incorrectly coded records.", "Create a clean outreach queue for staff review.", "Reconciles appointment, procedure, contact, and status evidence without clinical recommendations."],
  ["veterinary-followup-coordinator", "Vet Follow-up Queue", "Veterinary administration", "veterinary clinics", "Clinician-requested callbacks, rechecks, and result communications are scattered.", "Make every approved follow-up visible to the right staff member.", "Preserves clinician instructions and urgency while staying out of diagnosis and treatment."],
  ["salon-cancellation-fill", "ChairFill", "Appointment operations", "independent salons", "Staff manually message broad waitlists and risk double-booking or customer fatigue.", "Offer each opening to the smallest relevant set of willing clients.", "Matches service, provider, duration, timing preference, and consent in controlled waves."],
  ["home-inspection-explainer", "Inspection Clarity", "Home services", "home inspectors", "Buyers cannot distinguish observations, maintenance items, specialist questions, and urgency.", "Turn inspection reports into clear reading guides.", "Preserves the inspector's exact language and photos and makes uncertainty visible."],
  ["cleaning-estimate-scope", "CleanScope", "Cleaning services", "residential cleaning companies", "Quotes fail when condition, rooms, add-ons, access, and expectations are captured inconsistently.", "Create clear estimates with fewer scope surprises.", "Converts photos and answers into explicit inclusions, exclusions, and assumptions."],
  ["landscape-seasonal-planner", "Seasonal Yard Plan", "Landscaping operations", "landscape maintenance companies", "Generic calendars ignore property conditions, service scope, and observed changes.", "Turn each property into a living, contract-aware maintenance plan.", "Combines site inventory, season windows, contracted duties, and field observations."],
  ["tutor-progress-brief", "Tutor Progress Brief", "Education services", "independent tutors", "Session notes list activities without showing skill evidence or the next practice focus.", "Create concise, evidence-based progress updates.", "Separates observed performance from interpretation and avoids unsupported labels."],
  ["photo-shoot-list", "Shotlist Relay", "Creative services", "commercial photographers", "Must-have shots, usage needs, variants, approvals, and dependencies live in separate threads.", "Turn a client brief into a complete live shot list.", "Connects every shot to intended use, required variant, dependency, approver, and status."],
  ["catering-allergen-handoff", "Allergen Handoff", "Catering operations", "event caterers", "Dietary notes are paraphrased or lost between sales, kitchen, packing, and service.", "Preserve approved allergen instructions through each handoff.", "Records guest information verbatim, distinguishes preference, and requires qualified confirmation."],
  ["auto-estimate-explainer", "Repair Estimate Clarity", "Auto services", "independent repair shops", "Dense labor, parts, diagnostic, and optional-work lines confuse customers and delay approval.", "Turn a repair estimate into a clear approval conversation.", "Separates confirmed work, diagnostic next steps, maintenance, and customer-deferred items."],

  // Property and healthcare administration
  ["rent-roll-anomaly-check", "Rent Roll Check", "Property finance", "small property operators", "Duplicate charges, missing concessions, and lease-date mismatches survive spreadsheet review.", "Surface rent-roll exceptions with a traceable reason.", "Compares the current roll with lease terms, payments, prior movements, and approved adjustments."],
  ["hoa-request-tracker", "HOA Request Trail", "Community management", "homeowner associations", "Submissions, documents, questions, decisions, and deadlines get lost in email.", "Give every owner request a complete, neutral decision trail.", "Shows missing information, governing criteria, recusals, and timing without making decisions."],
  ["cam-charge-review", "CAM Charge Review", "Commercial leasing", "small commercial tenants", "Tenants cannot trace common-area charges to lease rules, caps, exclusions, and allocations.", "Organize a clause-linked CAM review for professional follow-up.", "Maps every arithmetic question to lease language and landlord statements without legal conclusions."],
  ["moveout-evidence-organizer", "Move-out Record", "Property operations", "small landlords and property managers", "Condition photos, work orders, dates, invoices, and communications cannot be aligned.", "Create a chronological, itemized turnover record.", "Timestamps and groups original evidence while avoiding legal conclusions about responsibility."],
  ["maintenance-triage-desk", "Maintenance Triage Desk", "Property operations", "small property managers", "Vague requests bounce between staff while urgent safety indicators can be missed.", "Collect the facts needed to route each maintenance request.", "Asks issue-specific questions and preserves human escalation for uncertain or urgent cases."],
  ["str-permit-calendar", "Stay Permit Calendar", "Short-term rental operations", "small vacation-rental operators", "Permit renewals, inspections, registrations, and filings vary by property and jurisdiction.", "Keep compliance dates visible with source-linked review.", "Records the source, effective date, property facts, reviewer, and submission evidence."],
  ["prior-auth-packet-checklist", "Authorization Packet Check", "Healthcare administration", "small specialty practices", "Payer submissions are delayed because forms, records, dates, and signatures are incomplete.", "Assemble complete administrative packets for clinician review.", "Checks configured documentation requirements without making coverage, coding, or clinical decisions."],
  ["clinic-no-show-recovery", "No-show Recovery", "Healthcare administration", "outpatient clinics", "Missed visits create fragmented outreach with little insight into access barriers.", "Coordinate respectful, policy-approved follow-up after missed appointments.", "Uses approved scheduling context, communication preferences, and no clinical inference."],
  ["caregiver-shift-handoff", "Care Shift Relay", "Care operations", "non-clinical home-care teams", "Schedule changes, household instructions, and operational tasks are lost between caregivers.", "Make each caregiver handoff concise, permissioned, and complete.", "Separates operational notes from clinical records and limits information by role."],
  ["lab-courier-chain", "Specimen Relay", "Healthcare logistics", "medical courier operations", "Pickup readiness, conditions, custody events, and delivery evidence are inconsistent.", "Capture an auditable transport chain for every assigned specimen.", "Follows laboratory procedures and escalates exceptions without judging specimen acceptability."],

  // Education, media, and creators
  ["syllabus-workload-map", "Syllabus Load Map", "Higher education", "college instructors", "Assignment dependencies and simultaneous deadlines create hidden workload peaks.", "See workload peaks before students encounter them.", "Models estimated effort, prerequisites, revision cycles, and overlap instead of counting due dates."],
  ["iep-meeting-organizer", "Meeting Evidence Organizer", "Education administration", "school support teams", "Reports, family questions, service logs, and procedural tasks are hard to assemble.", "Prepare a complete meeting packet without making educational decisions.", "Preserves source documents and access boundaries while leaving decisions to authorized teams."],
  ["apprenticeship-skill-log", "Apprentice Proofbook", "Workforce training", "trade apprenticeship programs", "Hours, task categories, supervisor approval, and skill evidence are recorded late.", "Keep a verifiable record of work-based learning.", "Distinguishes time exposure from demonstrated competence and authorized sign-off."],
  ["lab-equipment-booking", "LabSlot", "Research operations", "small academic labs", "Bookings ignore training status, setup time, maintenance windows, and abandoned reservations.", "Schedule instruments around readiness, not just availability.", "Validates authorization and setup requirements and captures actual use for capacity planning."],
  ["podcast-guest-research", "Guest Thread", "Podcast production", "independent interview podcasts", "Research becomes a biography recap instead of a map of fresh questions and source context.", "Build an interview brief that leads somewhere new.", "Ties angles to sources, avoids standard stories, and marks claims requiring verification."],
  ["media-license-expiry", "License Clock", "Media operations", "small creative teams", "Assets remain published after territory, channel, campaign, or time rights expire.", "Know where every licensed asset is used before rights change.", "Connects license clauses, derivatives, channels, territories, live uses, and expiration."],
  ["ugc-deliverable-tracker", "Creator Deliverable Board", "Creator marketing", "brands coordinating UGC campaigns", "Briefs, products, disclosures, drafts, usage rights, and payments drift across DMs.", "Keep every creator deliverable attached to its agreement.", "Tracks approval, disclosure, payment, and license scope as separate evidence-backed milestones."],
  ["brand-brief-translator", "Brief Translator", "Creative operations", "in-house marketing teams", "Requests arrive as channel lists and adjectives without audience, proof, constraints, or ownership.", "Convert fuzzy requests into actionable creative briefs.", "Asks only questions that change the work and exposes unresolved assumptions."],
  ["community-question-digest", "Community Signal", "Community operations", "software communities", "Important questions repeat across threads while loud conversations receive too much weight.", "Summarize recurring needs with links back to context.", "Weights recurrence, participant diversity, unresolved status, and product impact."],
  ["sponsorship-inventory-planner", "Sponsor Inventory", "Creator operations", "multi-format creators", "Placements, conflicts, capacity, delivery, and make-goods are tracked separately.", "Sell sponsorship capacity with one view of commitments.", "Models production workload and exclusivity conflicts alongside calendar inventory."],

  // Developer, data, and security operations
  ["saas-permission-drift", "Permission Drift", "IT operations", "small IT teams", "Roles accumulate after team changes, temporary projects, and copied permission groups.", "Find access that no longer matches current work.", "Compares permissions with role, usage, ownership, and approved exceptions."],
  ["api-changelog-impact", "ChangeImpact", "Developer operations", "teams depending on third-party APIs", "Provider deprecations are not mapped to the code and traffic that depend on them.", "Turn external API changes into owned impact checks.", "Links announcements to endpoints, SDKs, repositories, owners, and observed usage."],
  ["incident-evidence-pack", "Incident Evidence Pack", "Site reliability", "small engineering teams", "Logs, alerts, deploys, chat decisions, and customer impact are assembled after context fades.", "Build a source-linked incident timeline without rewriting history.", "Preserves original timestamps, marks uncertainty, and separates facts from hypotheses."],
  ["cloud-cost-owner-resolver", "Cloud Owner Resolver", "FinOps", "small engineering organizations", "Cost anomalies and stale resources cannot be acted on because owners and tags are missing.", "Identify the likely accountable team with transparent evidence.", "Combines infrastructure history, repositories, deployment identities, naming, and usage."],
  ["data-retention-map", "Retention Map", "Data governance", "small software companies", "Policy statements do not match backups, exports, logs, support tools, and deletion behavior.", "Connect retention promises to real systems and deletion evidence.", "Maps purpose, copies, triggers, configured deletion, holds, owners, and verification."],
  ["support-escalation-brief", "Escalation Brief", "Customer support", "technical support teams", "Engineering escalations include transcripts but omit reproduction, impact, environment, and the open question.", "Send engineering the smallest complete problem brief.", "Verifies evidence completeness and separates observed behavior from support hypotheses."],
  ["bug-reproduction-evidence", "Repro Proof", "Software quality", "product and support teams", "Customer bug reports omit sequence, state, version, environment, timing, and correlation details.", "Capture reproducible evidence without asking customers to debug.", "Adapts evidence requests to the failure and redacts sensitive data before sharing."],
  ["feature-flag-cleanup", "Flag Debt", "Developer productivity", "engineering teams", "Nobody knows whether old feature flags are active, permanent, abandoned, or safe to remove.", "Retire stale flags with runtime and code evidence.", "Joins evaluations, rollout state, owners, experiment decisions, code references, and dependencies."],
  ["data-contract-change", "Data Contract Relay", "Data engineering", "analytics teams", "A field can remain present while its meaning, units, timing, or allowed values change.", "Route data changes by downstream semantic impact.", "Compares producer intent, observed data, contracts, lineage, owners, and consumer assertions."],
  ["metric-definition-registry", "Metric Meaning", "Analytics governance", "growing companies", "Dashboards share metric names but differ in grain, timing, exclusions, and source tables.", "Make metric meaning and ownership inspectable.", "Versions the business question, calculation, grain, inclusion rules, owner, and trusted implementations."],
];

if (rows.length !== 100) {
  throw new Error("Expected 100 seed products, received " + rows.length);
}

function terms(slug: string, name: string, category: string, problem: string) {
  return Array.from(
    new Set(
      (slug + " " + name + " " + category + " " + problem)
        .toLowerCase()
        .replace(/[^a-z0-9 ]/g, " ")
        .split(/\s+/)
        .filter((word) => word.length > 2),
    ),
  ).slice(0, 14);
}

export const seedProducts: Product[] = rows.map((row, index) => {
  const [slug, name, category, audience, problem, promise, differentiator] = row;
  return {
    id: "seed-" + String(index + 1).padStart(3, "0"),
    slug,
    name,
    category,
    audience,
    problem,
    promise,
    differentiator,
    workflow: [
      "Collect the source records and context already used by " + audience + ".",
      "Surface the smallest set of exceptions or decisions that need attention.",
      "Record the owner, action, and outcome so the process becomes easier to improve.",
    ],
    keywords: terms(slug, name, category, problem),
    metrics: ["time from intake to a clear next action", "exceptions resolved with supporting evidence"],
    source: "seed",
    createdAt: "2026-09-05T00:00:00.000Z",
  };
});

export const seedProductBySlug = new Map(
  seedProducts.map((product) => [product.slug, product]),
);
